"""empty message

Revision ID: c77e9c95e042
Revises: 
Create Date: 2024-02-04 17:25:47.660141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c77e9c95e042'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('invitationCode', sa.String(), nullable=False),
    sa.Column('pw', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('invitationCode')
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pw', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('birthDay', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_group_association',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('group_invitationCode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_invitationCode'], ['group.invitationCode'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group_association')
    op.drop_table('user')
    op.drop_table('group')
    # ### end Alembic commands ###
